apiVersion: v2
name: csi-driver-dirpath
description: Node-local CSI driver for directory-backed scratch volumes
type: application
version: v0.1.0
appVersion: "v0.1.0"
home: https://github.com/KeenWill/csi-driver-dirpath
sources:
  - https://github.com/KeenWill/csi-driver-dirpath
